import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import "../globals.css";


export const metadata: Metadata = {
    title: "Main Layout",
    description: "Generated by create next app",
};


export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = {
        name: "j",
        followers: 2,
        avatar: "url"
    }
    return (
        <>
            <Navbar user={user} />
            <main className="min-h-screen p-4">
                {children}
            </main>
            {/* <Footer /> */}
        </>
    );
}
