import type { Metadata } from "next";
import { Logo } from "@/components/ui/logo";
import "../globals.css";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Onboarding",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="min-h-screen flex flex-col bg-[#fafafa]">
            <nav className="w-full px-6 py-4 h-16">
                <div className="max-w-7xl mx-auto h-full">
                    <div className="flex items-center h-full">
                        <Logo />
                    </div>
                </div>
            </nav>
            <main className="flex-grow flex items-center justify-center px-6">
                <div className="w-full max-w-7xl mx-auto">
                    {children}
                </div>
            </main>
            <footer className="w-full p-4 h-16">
                <div className="max-w-7xl mx-auto h-full flex items-center justify-center">
                    <div className="flex items-center justify-center gap-4 text-[13px] text-[#666666]">
                        <Link
                            href="/terms"
                            className="underline-offset-4 hover:underline"
                        >
                            Terms of Use
                        </Link>
                        <span className="text-[#cccccc]">Copyright BlackAt 2024</span>
                        <Link
                            href="/privacy"
                            className="underline-offset-4 hover:underline"
                        >
                            Privacy Policy
                        </Link>
                    </div>
                </div>
            </footer>
        </div>
    );
}

